name: "Build"

on:
  workflow_call:
    inputs:
      net_sdk:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    env:
      is_main_build: ${{ matrix.os == 'ubuntu-latest' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need full history for version number

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.net_sdk }}

      - name: "Build and test"
        run: dotnet run --project build/orchestrator -- --target=Default --dotnet-configuration=Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bundle"
        if: ${{ env.is_main_build }}
        run: dotnet run --project build/orchestrator -- --target=Bundle --dotnet-configuration=Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish artifacts to CI"
        if: ${{ env.is_main_build }}
        uses: actions/upload-artifact@v3
        with:
          name: "Artifacts"
          retention-days: 7
          path: |
            build/artifacts/
            !build/artifacts/docs

      - name: Publish docs artifact to CI
        if: ${{ env.is_main_build }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/artifacts/docs
