name: Build and release

on:
  # Dev
  workflow_dispatch:
  pull_request:
  push:
    # Preview
    branches: [ main ]
    # Stable
    tags: [ "v*" ]
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    uses: ./.github/workflows/build.yml
    with:
      agent_os: ${{ matrix.os }}
      net_sdk: '8.0.100'
      is_main_build: ${{ matrix.os == 'ubuntu-latest' }}

  # Preview release on push to main only
  # Stable release on version tag push only
  deploy:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      net_sdk: '8.0.100'
      azure_nuget_feed: 'https://pkgs.dev.azure.com/benito356/NetDevOpsTest/_packaging/Example-Preview/nuget/v3/index.json'
    secrets:
      #nuget_preview_token: ${{ secrets.NUGET_PREVIEW_TOKEN }}
      #nuget_stable_token: ${{ secrets.STABLE_NUGET_FEED_TOKEN }}
      azure_nuget_token: ${{ secrets.NUGET_PREVIEW_TOKEN }}
